### ISSUE TITLE
suggestion: css for scrolling vertically overflowing slides using css container queries

### ISSUE THREAD

**Issue by TheophileDesmedt** [kookma/TW-Tamasha#25]
```css
.tamasha-slide-content{
container-type: size;
overflow-y: scroll;
}
.tamasha-overlay.open .tamasha-slide-content{
position:absolute;
inset:0;
max-height:100cqh;
}
```

With this it is no longer needed to use a wrapper div ([as seen here](https://kookma.github.io/TW-Tamasha/#Long%20List%20With%20Scrollbar)) , and the height take as much space as possible.
